---
- name: cisco Device provisioning
  hosts: lab
  connection: network_cli
  gather_facts: False

  pre_tasks:
    - name: Create target directory
      file: path=/var/tmp/ansible/{{ inventory_hostname }} state=directory mode=0755
      check_mode: no
      tags: always
      changed_when: False

  roles:
    - device_provisioning
      #    - vlans
      #- interfaces
    - commit

